# Generated by Django 2.2.6 on 2020-07-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_auto_20200701_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
